replicaCount: 1

image:
  repository: docker pull homeassistant/home-assistant
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: True
  annotations:
     kubernetes.io/ingress.class: nginx
  hosts:
    - host: homeassistant.grubbr.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local