replicaCount: 1

image:
  repository: ghcr.io/home-assistant/home-assistant
  pullPolicy: IfNotPresent
  tag: "stable"
  env:
    - name: TZ
      value: "America/Denver"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: True
  annotations:
     kubernetes.io/ingress.class: nginx
  hosts:
    - host: homeassistant.grubbr.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local