app:
  name: home-assistant

deployment:
  name: home-assistant
  replicas: 1
container:
  name: home-assistant
  image: ghcr.io/home-assistant/home-assistant
  tag: IfNotPresent
  port: 8123
  volumeMounts:
    - mountPath: /config
      subPath: config/home-assistant
  env:
    TZ: America/Denver

service:
  name: home-assistant-service
  ports:
    http:
      port: 443
      targetPort: 8123
      protocol: TCP

volumes:
  name: data
  nfs:
    server: 192.168.0.40
    path: /data

ingress:
  enabled: true
  name: home-assistant-ingress
  annotations:
    rewriteTarget: /home-assistant/$2
    useRegex: "true"
  className: nginx
  host: grubbr.io
  path: /home-assistant(/|$)
  tlsSecret: home-assistant-tls