app:
  name: home-assistant

deployment:
  name: home-assistant
  replicas: 1
container:
  name: home-assistant
  image: ghcr.io/home-assistant/home-assistant
  tag: IfNotPresent
  port: 8123
  volumeMounts:
    - mountPath: /config
      subPath: config/home-assistant
  env:
    TZ: America/Denver

service:
  name: home-assistant-service
  ports:
    http:
      port: 443
      targetPort: 8123
      protocol: TCP

volume:
  name: data
  storage: 100Gi

ingress:
  enabled: true
  name: home-assistant-ingress
  annotations:
    rewriteTarget: /homeassistant/$2
    useRegex: "true"
  className: nginx
  host: grubbr.io
  path: /homeassistant(/|$)(
  tlsSecret: home-assistant-tls