app:
  name: transmission

deployment:
  name: transmission
  replicas: 1

container:
  name: transmission
  image: lscr.io/linuxserver/transmission
  tag: latest
  ports: [9091, 51413]
  env:
    TRANSMISSION_HOME: /config
    TZ: America/Denver
    PUID: 911
    PGID: 911

service:
  name: transmission-service
  ports:
    http:
      port: 443
      targetPort: 9091
      protocol: TCP
    tcp:
      port: 51413
      targetPort: 51413
      protocol: TCP
    udp:
      port: 51413
      targetPort: 51413
      protocol: UDP

ingress:
  enabled: true
  name: transmission-ingress
  annotations:
    rewriteTarget: /transmission/$2
    useRegex: "true"
  className: nginx
  host: grubbr.io
  path: /transmission(/|$)(

