app:
  name: transmission

deployment:
  name: transmission
  replicas: 1

container:
  name: transmission
  image: lscr.io/linuxserver/transmission
  tag: latest
  ports: [9091, 51413]
  volumeMounts:
    - mountPath: /config
      subPath: config/transmission
    - mountPath: /downloads
      subPath: downloads
  env:
    TRANSMISSION_HOME: /config
    TZ: America/Denver
    PUID: 911
    PGID: 911

service:
  name: transmission-service
  ports:
    http:
      port: 443
      targetPort: 9091
      protocol: TCP

volume:
  name: data
  storage: 100Gi

ingress:
  enabled: true
  name: transmission-ingress
  annotations:
    rewriteTarget: /transmission/$2
    useRegex: "true"
  className: nginx
  host: grubbr.io
  path: /transmission(/|$)(.*)
  tlsSecret: transmission-tls

