replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "stable"

service:
  type: ClusterIP
  ports:
    - name: udp
      port: 34197
      protocol: UDP
    - name: tcp
      port: 27015
      protocol: TCP

ingress:
  enabled: True
  className: "nginx"
  annotations:
     kubernetes.io/ingress.class: nginx
  hosts:
    - host: factorio
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local