apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image}}:{{ .Values.container.tag }}
          ports:
            - containerPort: {{index .Values.container.port}}
          volumeMounts:
            {{- range $key, $value := .Values.container.volumeMounts }}
            - name: {{ $.Values.volume.name }}
              mountPath: {{ $value.mountPath }}
              subPath: {{ $value.subPath }}
            {{- end }}
          env:
            {{- range $key, $value := .Values.container.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
      volumes:
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.deployment.name }}-pvc