apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
    - name: tcp
      protocol: TCP
      port: {{ .Values.service.ports.tcp.port }}
      targetPort: {{ .Values.service.ports.tcp.targetPort }}
    - name: udp
      protocol: UDP
      port: {{ .Values.service.ports.udp.port }}
      targetPort: {{ .Values.service.ports.udp.targetPort }}
